# Application Configuration
spring.application.name=tasks
spring.profiles.active=postgres
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
# RabbitMQ Configuration
spring.rabbitmq.host=tasks-rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=1000
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.max-interval=10000
spring.rabbitmq.listener.simple.retry.multiplier=2.0